# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('block', models.CharField(choices=[('cc1', 'COMPUTER CENTER- 1'), ('cc2', 'COMPUTER CENTER- 2'), ('cc3', 'COMPUTER CENTER- 3'), ('lt', 'LECTURE THEATRE')], max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('floor_number', models.PositiveIntegerField(verbose_name='Floor number')),
                ('maximum_capacity', models.PositiveIntegerField(verbose_name='Maximum room size')),
                ('projector', models.BooleanField(choices=[(True, 'WORKING'), (False, 'NOT WORKING')], max_length=10, verbose_name='Projector condition')),
                ('computer', models.BooleanField(choices=[(True, 'WORKING'), (False, 'NOT WORKING')], max_length=10, verbose_name='Computer condition')),
                ('air_conditioner', models.BooleanField(choices=[(True, 'WORKING'), (False, 'NOT WORKING')], max_length=10, verbose_name='AC condition')),
                ('speakers', models.BooleanField(choices=[(True, 'WORKING'), (False, 'NOT WORKING')], max_length=10, verbose_name='Speakes condition')),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('block', models.CharField(choices=[('cc1', 'COMPUTER CENTER- 1'), ('cc2', 'COMPUTER CENTER- 2'), ('cc3', 'COMPUTER CENTER- 3'), ('lt', 'LECTURE THEATRE')], max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('floor_number', models.CharField(max_length=10, verbose_name='Floor number')),
                ('maximum_capacity', models.CharField(max_length=5, verbose_name='Maximum room size')),
                ('type', models.CharField(choices=[('computer', 'COMPUTER'), ('physics', 'PHYSICS'), ('vlsi', 'VLSI')], max_length=20, verbose_name='Type of Lab')),
                ('air_conditioner', models.BooleanField(choices=[(True, 'WORKING'), (False, 'NOT WORKING')], max_length=10, verbose_name='AC condition')),
            ],
        ),
        migrations.CreateModel(
            name='requestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, verbose_name='time stamp')),
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('block_type', models.CharField(choices=[('classroom', 'CLASSROOM'), ('lab', 'LAB')], default='classroom', max_length=10, verbose_name='Block type')),
                ('startDateTime', models.CharField(max_length=30, verbose_name='startDateTime')),
                ('endDateTime', models.CharField(max_length=30, verbose_name='endDateTime')),
                ('sender', models.CharField(max_length=20, verbose_name='sender')),
                ('sender_id', models.CharField(default='', max_length=20, verbose_name='sender_id')),
                ('granter', models.CharField(blank=True, max_length=10, verbose_name='granter')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('booking_status', models.CharField(default='0', max_length=5, verbose_name='booking status')),
            ],
        ),
    ]
