# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_classroom_labs_requesttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('course', models.CharField(max_length=25, verbose_name='course name')),
                ('startTime', models.CharField(default='', max_length=30, verbose_name='start time')),
                ('endTime', models.CharField(default='', max_length=30, verbose_name='end time')),
                ('dayOfWeek', models.CharField(max_length=12, verbose_name='week day')),
                ('lecturer', models.CharField(max_length=10, verbose_name='lecturer')),
            ],
        ),
    ]
